language: node_js
node_js:
  - '15.2.1'
script:
  - yarn run build
  - yarn run test
deploy:
  provider: npm
  api_token: fsL62MdA9xivBNabjS2vKfmR8NJhjDAw1Gf+9Py6i2fei+UwICpNOAOU5Tc7Scd/KOGU7W7JlVj3ZnfHrvL1iRpJQLGScrGVq1iYYTOOv7jNiK2afQxp+s//273AIYdZUqehX3DNY8ATSKSlEUjy1ksIdLR3nB6uFQc7Y9NUZ7WNWlOKdnFGKZw2rUvVqfsfgHbr11yizeOgFOs1w12ustUVZDzEA5twxV4O/KlQ0s2pTUq3Y8iwTyoh2S3bY1LZ72j8+lsbNw2M7BnMjJBJxjKRwiAySfyv6cld4VgVz5NBxPlJomb5d5T+Qb15+L0iGSwk//JtmdpNhi/hVCspEFsnsQn3Zes+8o4TZPn7ZpolmQRrP2eX72i2n+PfrYnwwgOf3Ywl1csw7GkDdsbIsP9mz05ym/LyvJYySUlSIBcuKgaxiE553LnNMZRyYleqO1k8h4VyNC4N3xoFp/iYUjgLKK640iMYC0Scu62dE4NHHT7UIanhY3xMxtJOcbKg837+hBW/bYgZWLI0yqrR2DjgSjQO1X+EOO3r3+e9Fn/kb0BUac/ulDqjLLBvIggm58AW40wdGfiXHWES1evw/CHdFoV4bg+BeFBVvhTAHTcs4kd5c9Pg54pWmwmMHMMgQ/rHBRaw+8cfsbfQLrvzI+ypBNnLF8aCvMSNZubB+c4=
  edge: true # opt in to dpl v2
